// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate Supabase configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '❌ Supabase configuration missing!\n\n' +
      'Please set the following environment variables in your .env file:\n' +
      '- VITE_SUPABASE_URL (your Supabase project URL)\n' +
      '- VITE_SUPABASE_PUBLISHABLE_KEY (your Supabase anon/public key)\n\n' +
      'Get these from: https://app.supabase.com → Your Project → Settings → API'
  );
}

// Check if URL is pointing to Lovable (common mistake)
if (SUPABASE_URL.includes('lovable') || SUPABASE_URL.includes('loveable')) {
  console.error(
    '⚠️ WARNING: Your VITE_SUPABASE_URL appears to be pointing to Lovable!\n' +
      'Please update your .env file with your actual Supabase project URL.\n' +
      'Get your Supabase URL from: https://app.supabase.com → Your Project → Settings → API'
  );
}

// Validate Supabase URL format
if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
  console.warn(
    '⚠️ WARNING: Your VITE_SUPABASE_URL does not appear to be a valid Supabase URL.\n' +
      'Expected format: https://xxxxx.supabase.co\n' +
      'Current value: ' +
      SUPABASE_URL
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
